### ISSUE TITLE
smo - rad - diffuse_BW has dropouts

### ISSUE THREAD

**Issue by hagne** [hagne/data_baseline#15]
There are extended data gaps which became longer and more frequent in recent weeks

![](https://www.esrl.noaa.gov/gmd/webdata/grad/obs/smo/2018/gradobs.smo-rad.20181021.quicklook.jpg)

**Comment by gmd-jw** [comment]
SMO tracker not operational due to Garmin GPS firmware bug. This makes the diffuse operate like a global instrument, except the logger is programmed for a lower expected signal from the diffuse. This causes the signal to over-range (missing data). An interim fix has been sent to SMO, but it will take 7-10 days to arrive.

**Comment by hagne** [comment]
13 days have passed and the problem is still there, any news?

**Comment by gmd-jw** [comment]
Comms cable sent by FedEx using International Priority, but still has not arrived. Once it arrives we will be able to get the tracker operational without the GPS.

Garmin has sent a firmware fix that appears to work. We will update one of the GPS and ship to SMO. However, it will take a couple weeks (at least).

**Comment by gmd-jw** [comment]
Tracker should be working again.

**Comment by hagne** [comment]
diffuseBW is still dropping out.
![](https://raw.githubusercontent.com/hagne/data_baseline/master/issue_figures/smo_rad_diffuseBW_still_dropping_out.png)
