### ISSUE TITLE
ber - met - RH value looks strangly low

### ISSUE THREAD

**Issue by hagne** [hagne/data_baseline#21]
Shouldn't Bermuda be a rather humid place? Its always below ~35%. Is that an instrument or a data processing/calibration issue?

![](https://www.esrl.noaa.gov/gmd/webdata/grad/obs/ber/2018/gradobs.ber-met.20181022.quicklook.jpg)

**Comment by hagne** [comment]
looks like it was fixed on 11/20/2018

**Comment by gmd-jw** [comment]
Matt checked the sensor and said that he found a little corrosion that he cleaned off from the connector. However, the corrosion may have been the contact grease we use. Regardless, the data looks reasonable now. A spare sensor has been ordered and will be sent to Bermuda.

**Comment by gmd-jw** [comment]
Yup. Matt checked the sensor and said that he found a little corrosion 
that he cleaned off from the connector. However, the corrosion may have 
been the contact grease we use. Regardless, the data looks reasonable 
now. Instead of sending them a new humidity element, I have decided to 
send them a complete new sensor as a spare to set on the shelf in case 
it acts up again.


Jim

**Comment by gmd-jw** [comment]
I submitted a new issue with a ceilometer. I think it would be good to 
pull Christian into the GitHub system. He will be managing the 
ceilometers for SURFRAD.
I have already fixed the problem, but I will leave it open so that 
Christian can close it.

Jim
