### ISSUE TITLE
SMO - rad - global is dead

### ISSUE THREAD

**Issue by hagne** [hagne/data_baseline#39]
![](https://raw.githubusercontent.com/hagne/BaselineObsLog/master/issue_figures/Screenshot_20200218_162827.png)
global died: https://www.esrl.noaa.gov/gmd/grad/obs/obsplot.php?sta=smo&type=cal

**Comment by emielhall** [comment]
Tim found that the Global sensor signal cable was pulled out of the data logger. He rewired the signal cable into the logger on 27FEB2020.

He also installed the new solar tracker control box and gray cable to try and resolve the tracker issues. The new box did not fix the tracker so we will continue to try and diagnose the solar tracker issue.

**Comment by emielhall** [comment]
The issue with the Global pyranometer looks to be resolved after Tim wired the signal cable back into the logger. The Direct beam stopped working on 2020/02/29 (-99999 in the raw data files). Today I emailed Tim and asked him to check on the NIP and the signal cable/logger.

**Comment by emielhall** [comment]
Tim was able to get the solar tracker working again on 2020/03/05. There was a loose coupler that attaches the elevation motor to the elevation worm gear. Once the coupler set screws were tightened down, the tracker was able to reset properly and then begin to track the sun again. The Direct looks to be working properly again now that the solar tracker is functioning.

**Comment by hagne** [comment]
Most things look pretty good now. Only the fan of the diffuse is still not reporting. @emielhall  Any new about that?

**Comment by emielhall** [comment]
The fan was working properly last week according to Tim. He had to change channels on the fan multiplexer but Jim didn't know to change the logger program to reflect the change. Jim now knows about the change and will fix it when he has time.

**Comment by hagne** [comment]
@gmd-jw  Jim, I was wondering if you had time to work on the change mentioned by Emiel above.

**Comment by emielhall** [comment]
I think the issue turned out to be that the fan multiplexer needed a new wire connecting to the data logger to use the higher number channels that Tim connected the power cable into. We don't normally need to use those higher channels, so we don't connect that extra wire in our typical builds. I think Jim asked Tim to add this wire, but I don't remember what happened after that. Maybe he didn't have the supplies? Or maybe just forgot to do it. I can check in with Tim to see if he is able to do this for us.

**Comment by gmd-jw** [comment]
The mux needs another wire ran from the logger to the fan mux. I 
provided instructions to Tim on 3/10. I uploaded the new firmware into 
the logger on 3/11 so that once the wire is installed the new fan tach 
should start coming in. If Tim has added the wire, then there may be a 
problem with the code I uploaded.

Emiel - Please see if Tim added the wire.

Thanks,
Jim

PS - Here are the instructions I sent to Tim.
> To measure the fan tach on all of the 8 fan mux ports, we will need 
> you to run a wire from the "C2" terminal on the fan mux board to the 
> "C3" terminal on the CR10X data logger.


emielhall wrote on 4/8/2020 22:12:

**Comment by emielhall** [comment]
On 2020/04/09 Tim ran the new wire from the fan mux to the data logger. After Jim modified the program to reflect the changes we were able to get the tach data from all three fans. Unfortunately the diffuse ventilator fan was very noisy. Tim inspected the fan and found a broken pin inside the cable. Tim and Futi routed a new cable from the ventilator to the fan mux on 2020/04/13. As of 0100 UTC on 2020/04/14 all three fans are stable and reading normal RPM. I will continue to monitor the fan tach to make sure the fans continue to work properly.

**Comment by emielhall** [comment]
All fans are spinning and stable RPM. I think this ticket can be closed.
