### ISSUE TITLE
BRW - rad - upwelling longwave fan is dying

### ISSUE THREAD

**Issue by hagne** [hagne/data_baseline#42]
![](https://raw.githubusercontent.com/hagne/BaselineObsLog/master/issue_figures/BRW%20-%20rad%20-%20upwelling%20longwave%20fan%20is%20dying.png)

**Comment by emielhall** [comment]
Fan was swapped out by Peter on 10MAR2020, but that didn't fix the issue. He tested the "dead" fan inside and said it was still working, so likely an issue with the cable or mux. Due to weather, they couldn't get out to the tower until yesterday (16MAR2020). They inspected the cable, connectors and mux and noticed damage to the bulkhead connector on the ventilator housing. Peter is planning to replace the connectors on the cable and ventilator with 3pin Amphenol connectors. Jim requested pictures to document the work so that we can be prepared to replace the ventilator housings next time we visit the station. I will update the outcome when they have finished the work on site.

**Comment by emielhall** [comment]
Peter fixed the connector issue and remounted the instrument on 17MAR2020. Everything looks to be back to normal after watching the fan and instrument signal for a couple days. I think this issue can be closed.

**Comment by hagne** [comment]
agreed!
