### ISSUE TITLE
SMO - rad - direct normal is dead

### ISSUE THREAD

**Issue by hagne** [hagne/data_baseline#43]
![](https://raw.githubusercontent.com/hagne/BaselineObsLog/master/issue_figures/SMO%20-%20rad%20-%20direct%20normal%20is%20dead.png)

**Comment by emielhall** [comment]
I emailed Tim and Vai in Samoa asking them to start tests to diagnose the issue. Visual inspection of the instrument, connectors, and cables first. Then installing the instrument simulator test box to decide if it's an instrument issue or a cable/acquisition problem. Tim is off island until 17MAR2020 according to the automatic message I received, so it might be a day or two before they start working on this.

**Comment by emielhall** [comment]
No word from Samoa yet. This is an intermittent problem, direct data is back to normal as of 2020/03/17 (~16:15) until current.

**Comment by emielhall** [comment]
On 2020/03/24 Tim checked the data logger and found a loose wire on the direct beam signal cable. He tightened down the screw terminals for that cable to see if that would help resolve the issue. I have been checking the data regularly since then and haven't seen anymore -99999 data for the SMO direct beam. Since the problem was intermittent to begin with, I'm not 100% sure this is fixed. But so far it seems like this fixed the issue.

**Comment by hagne** [comment]
I specifically looked out for intermittent dropouts over the last week or so and have not seen any. I guess its time to close this issue.
